Repository meateam/file-service, pull requests merged in 2019-07, with the labels that each got.

#87 Feature/apm
  package-lock.json
  package.json
  src/config.ts
  src/file/file.model.ts
  src/file/file.rpc.ts
  src/utils/errors/application.error.ts
  src/utils/errors/grpc.status.ts
  tslint.json
Labels: feature

#89 Feature/logging
  package-lock.json
  package.json
  src/config.ts
  src/file/file.rpc.ts
  src/utils/logger.ts
Labels: feature

#96 Refactor/stem
  .vscode/launch.json
  package-lock.json
  package.json
  src/config.ts
  src/file/file.grpc.ts
  src/file/file.interface.ts
  src/file/file.rpc.ts
  src/file/file.service.ts
  src/index.ts
  src/server.ts
  src/upload/upload.grpc.ts
  src/utils/logger.ts
  src/utils/spec.helper.ts
Labels: refactor

#98 Refactor: repository and service
  src/file/file.repository.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
  src/quota/quota.interface.ts
  src/quota/quota.repository.ts
  src/upload/upload.grpc.ts
  src/upload/upload.service.ts
Labels: refactor

#99 Added nyc
  .gitignore
  .nycrc
  package-lock.json
  package.json
  src/utils/errors/file.ts
  src/utils/errors/folder.ts
  src/utils/spec.helper.ts
Labels: feature, refactor

#109 implemented delete to file and folder
  src/file/file.interface.ts
  src/file/file.model.ts
  src/file/file.repository.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
Labels: feature

#110 Hotfix/key thrown
  src/file/file.model.ts
  src/file/file.repository.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
  src/quota/quota.model.ts
  src/upload/upload.model.ts
  src/utils/errors/client.error.ts
Labels: bug

#112 Feature/update file
  Dockerfile
  mocha.opts
  proto/file.pb.go
  proto/file.proto
  src/file/file.grpc.ts
  src/file/file.model.ts
  src/file/file.repository.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
  src/index.ts
  src/server.ts
  src/utils/logger.ts
Labels: enhancement, feature

#111 Feature/get folders
  package-lock.json
  package.json
  proto/file.pb.go
  proto/file.proto
  src/file/file.grpc.ts
  src/file/file.interface.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
  src/utils/errors/client.error.ts
Labels: feature

#113 Feature/get descendants
  proto/file.pb.go
  proto/file.proto
  src/file/file.grpc.ts
  src/file/file.interface.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
  src/server.ts
Labels: feature
