Repository meateam/file-service, pull requests merged in 2019-08, with the labels that each got.

#116 Changed getDescendants return value
  src/file/file.grpc.ts
  src/file/file.interface.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
Labels: bug

#121 Hotfix/unique index
  src/file/file.model.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
  src/utils/spec.helper.ts
Labels: bug

#123 Feature/update file
  src/file/file.service.ts
Labels: bug

#124 Feature/delete folder
  proto/file.pb.go
  proto/file.proto
  src/file/file.grpc.ts
  src/file/file.interface.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
Labels: feature, file service

#126 fixed error message for #118
  src/file/file.model.ts
Labels: bug

#129 fixed extractQuery and added test #128
  src/file/file.service.spec.ts
  src/file/file.service.ts
Labels: bug

#134 Added test for folder name with space in it #133
  src/file/file.service.spec.ts
Labels: bug

#131 Hotfix/logger
  src/file/file.grpc.ts
  src/server.ts
  src/utils/logger.ts
Labels: bug

#141 fixed bug in wrapper
  src/utils/logger.ts
Labels: bug

#142 refactor
  src/file/file.service.spec.ts
  src/file/file.service.ts
Labels: refactor

#144 fixed quota update on delete, added to tests #132
  src/file/file.service.spec.ts
  src/file/file.service.ts
  src/quota/quota.repository.ts
  src/quota/quota.service.ts
Labels: bug

#146 Feature/is allowed
  proto/file/file.pb.go
  proto/file/file.proto
  proto/go.mod
  proto/quota/quota.pb.go
  proto/quota/quota.proto
  src/file/file.service.spec.ts
  src/file/file.service.ts
  src/quota/quota.grpc.ts
  src/quota/quota.service.ts
  src/server.ts
Labels: feature

#147 fixed proto path
  src/server.ts
Labels: bug

#148 updated proto and README accordingly
  README.md
  proto/file/file.pb.go
  proto/go.mod
  proto/go.sum
  proto/quota/quota.pb.go
Labels: bug

#151 added quota limitation and envVar #149
  src/config.ts
  src/file/file.service.spec.ts
  src/quota/quota.model.ts
Labels: feature
