Repository meateam/file-service, pull requests merged in 2019-06, with the labels that each got.

#58 Hotfix/filename
  proto/file.proto
  src/file/file.interface.ts
  src/file/file.model.ts
  src/file/file.repository.ts
  src/file/file.rpc.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
Labels: bug, file service

#64 Hotfix/root folder
  src/file/file.interface.ts
  src/file/file.model.ts
  src/file/file.repository.ts
  src/file/file.rpc.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
Labels: bug

#65 Hotfix/status codes
  src/utils/errors/application.error.ts
  src/utils/errors/client.error.ts
  src/utils/errors/file.ts
  src/utils/errors/folder.ts
Labels: bug

#68 should fix #67
  src/file/file.interface.ts
  src/file/file.repository.ts
  src/file/file.rpc.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
Labels: bug

#66 Develop
  .snyk
  docker-compose.yml
  package-lock.json
  package.json
  proto/file.pb.go
  proto/file.proto
  src/config.ts
  src/file/file.interface.ts
  src/file/file.model.ts
  src/file/file.repository.ts
  src/file/file.rpc.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
  src/file/upload.model.ts
  src/server.ts
  src/utils/errors/application.error.ts
  src/utils/errors/client.error.ts
  src/utils/errors/file.ts
  src/utils/errors/folder.ts
  src/utils/spec.helper.ts
Labels: bug, enhancement, feature

#69 Hotfix/update upload
  proto/file.pb.go
  proto/file.proto
  src/file/file.interface.ts
  src/file/file.rpc.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
  src/file/upload.interface.ts
  src/file/upload.model.ts
  src/file/upload.repository.ts
Labels: bug

#75 add check before splitting strings
  src/file/file.model.ts
  src/file/file.service.ts
Labels: bug

#76 Feature/limit storage
  .gitignore
  .vscode/launch.json
  docker-compose.yml
  proto/file.pb.go
  proto/file.proto
  src/file/file.interface.ts
  src/file/file.model.ts
  src/file/file.repository.ts
  src/file/file.rpc.spec.ts
  src/file/file.rpc.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
  src/quota/quota.interface.ts
  src/quota/quota.model.ts
  src/quota/quota.repository.ts
  src/quota/quota.service.ts
  src/upload/upload.interface.ts
  src/upload/upload.model.ts
  src/upload/upload.repository.ts
  src/utils/errors/quota.error.ts
  test.Dockerfile
Labels: bug, enhancement, feature

#77 Develop
  .gitignore
  .vscode/launch.json
  docker-compose.yml
  proto/file.pb.go
  proto/file.proto
  src/file/file.interface.ts
  src/file/file.model.ts
  src/file/file.repository.ts
  src/file/file.rpc.spec.ts
  src/file/file.rpc.ts
  src/file/file.service.spec.ts
  src/file/file.service.ts
  src/quota/quota.interface.ts
  src/quota/quota.model.ts
  src/quota/quota.repository.ts
  src/quota/quota.service.ts
  src/upload/upload.interface.ts
  src/upload/upload.model.ts
  src/upload/upload.repository.ts
  src/utils/errors/quota.error.ts
  test.Dockerfile
Labels: bug, enhancement, feature, file service, good first issue, refactor, test

#81 add connection string to mongo connection
  src/config.ts
  src/file/file.rpc.ts
  src/file/file.service.spec.ts
  src/server.ts
Labels: bug, feature

#82 Feature/health check
  Dockerfile
  package-lock.json
  package.json
  src/file/file.rpc.ts
  src/server.ts
Labels: feature
